server:
  port: 8080
  contextPath: /BookStoreApplication
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/bookstore_db?zeroDateTimeBehavior=convertToNull
    username: root
    password: 1q2w3e
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect:  org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/bookstore_db?zeroDateTimeBehavior=convertToNull
    username: root
    password: 1q2w3e
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect